Neplex trading/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Neplex_trading.Data;
using Neplex_trading.Models;
using Neplex_trading.ViewModels;
using ReflectionIT.Mvc.Paging;

namespace Neplex_trading.Controllers
{
    public class ProductsController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IHostingEnvironment _hostingEnv;

        public ProductsController(AppDbContext context,IHostingEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnv = hostingEnvironment;
        }


        public IActionResult AdminIndex() {
           var products= _context.Products.Include(c=>c.Category);
            return View(products);
        }

        public IActionResult ProductSearch(string searcheditem)
        {
            var query = from x in _context.Products select x;
            if (!String.IsNullOrEmpty(searcheditem))
            {
                query = query.Where(x => x.ProductName.Contains(searcheditem));
            }

            if (query.Any())
                return View(query.AsNoTracking().ToList());
            
            return View("NotFound");

        }

        // GET: Products
        [Obsolete]
        public async Task<IActionResult> Index(int  page=1)
        {
            var item = _context.Products.AsNoTracking().OrderBy(p => p.ProductName);
            var model = await PagingList<Product>.CreateAsync(item,12,page);
          
            ViewBag.category = _context.Categories;
           
            return View(model);
        }

        // GET: Products/Details/5
        public  IActionResult Details(int? id)
        {
            Product product = _context.Products.Find(id);
            if(product==null)
            {
                return View("NotFound");
            }
           
            var relproducts = _context.Products.Where(p => p.CategoryId == product.CategoryId).ToList();

            if (product == null)
            {
                return View("NotFound");
            }

            DetailsProductVM model = new DetailsProductVM {
            
            Product = product,
            RelatedProducts = relproducts
            };


            return View(model);
        }





        [Authorize(Roles = "Admin")]
        public IActionResult Create()
        {
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CartegoryId", "Name");
            return View();
        }

       

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin")]
        public IActionResult Create(ProductsVM model)
        {

            if (ModelState.IsValid)
            {
                string uniqueFileName = null;
                if (model.Photo != null)
                {
                    string uploadFolder = Path.Combine(_hostingEnv.WebRootPath, "img");
                    uniqueFileName = Guid.NewGuid() + "_" + model.Photo.FileName;
                    string filePath = Path.Combine(uploadFolder, uniqueFileName);
                    model.Photo.CopyTo(new FileStream(filePath, FileMode.Create));
                }

                Product newProduct = new Product
                {
                    ProductName = model.ProductName,
                    ProductImage = uniqueFileName,
                    ProductArtNumber= model.ProductArtNumber,
                    ProductDescription = model.ProductDescription,
                    CategoryId = model.CategoryId
                };
                ViewData["CategoryId"] = new SelectList(_context.Categories, "CartegoryId", "Name", model.CategoryId);


                _context.Products.Add(newProduct);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(model);

        }




        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }

            EditProductVM editProductVM = new EditProductVM { 
                
                ProductId=product.ProductId,
                ProductName= product.ProductName,
                ProductDescription = product.ProductDescription,
                ProductArtNumber = product.ProductArtNumber,
                ExistingPhoto = product.ProductImage,
                IsFeatured = product.IsFeatured,
                InStock = product.InStock,
                CategoryId = product.CategoryId

            };

            ViewData["CategoryId"] = new SelectList(_context.Categories, "CartegoryId", "Name", product.CategoryId);
            return View(editProductVM);
        }




        [Authorize(Roles = "Admin")]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(EditProductVM model)
        {
            Product product = _context.Products.Find(model.ProductId);
            if (product == null)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (model.Photo != null)
                {
                    if (model.ExistingPhoto != null)
                    {
                        string filePath = Path.Combine(_hostingEnv.WebRootPath,
                            "img", model.ExistingPhoto);
                        System.IO.File.Delete(filePath);
                    }

                    string uniqueFileName = null;

                    if (model.Photo != null)
                    {
                        string uploadsFolder = Path.Combine(_hostingEnv.WebRootPath, "img");
                        uniqueFileName = Guid.NewGuid().ToString() + "_" + model.Photo.FileName;
                        string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                        using (var fileStream = new FileStream(filePath, FileMode.Create))
                        {
                            model.Photo.CopyTo(fileStream);
                        }

                        product.ProductImage = uniqueFileName;

                    }

                }
                        product.ProductName = model.ProductName;
                        product.ProductArtNumber = model.ProductArtNumber;
                        product.ProductDescription = model.ProductDescription;
                        product.CategoryId = model.CategoryId;
                        product.Price = model.Price;
                        product.IsFeatured = model.IsFeatured;
                        product.InStock = model.InStock;
                    
                    ViewData["CategoryId"] = new SelectList(_context.Categories, "CartegoryId", "Name", model.CategoryId);


                    _context.Products.Update(product);
                    _context.SaveChanges();

                    return RedirectToAction("Index");

                
            }
            ViewData["CategoryId"] = new SelectList(_context.Categories, "CartegoryId", "Name", model.CategoryId);
            return View(model);
        }





        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Category)
                .FirstOrDefaultAsync(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }





        [Authorize(Roles = "Admin")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.ProductId == id);
        }
    }
}

Neplex trading/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Neplex_trading.Data;
using Neplex_trading.Data.Models;
using Neplex_trading.ViewModels;

namespace Neplex_trading.Controllers
{
    public class ShoppingCartController : Controller
    {
        private AppDbContext _context;
        private ShoppingCart _cart;

        public ShoppingCartController(AppDbContext context, ShoppingCart cart)
        {
            _context = context;
            _cart = cart;
        }
        public IActionResult Index()
        {
            var items = _cart.GetShoppingCartItems();
            _cart.ShoppingCartItems = items;

            var shoppingCartVM = new ShoppingCartVM {
                    ShoppingCart = _cart,
                    ShoppingCartTotal = _cart.GetShoppingCartTotal()
            };
            return View(shoppingCartVM);
        }

       [HttpGet]
        public IActionResult UpdateCart(int id,int amount) {

            var item = _context.ShoppingCartItems.Find(id);
            if (item != null)
            {
                
                item.Amount = amount;
            }
            else
            {
                return View("NotFount");
            }
            _context.ShoppingCartItems.Update(item);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }



        public IActionResult AddToShoppingCart(int id)
        {

            var selectedItem = _context.Products.Find(id);
            if (selectedItem != null)
            {
                _cart.AddToCart(selectedItem, 1);
            }
            return RedirectToAction("Index");
        }




        public IActionResult RemoveFromShoppingCart(int id)
        {
            var selectedItem = _context.Products.Find(id);
            if (selectedItem != null)
            {
                _cart.RemoveFromCart(selectedItem);
            }
            return RedirectToAction("Index");
        }
















    }
}

Neplex trading/Views/ShoppingCart/Index.cshtml
@model ShoppingCartVM

<div class="breadcrumbs">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="container-inner">
                    <ul>
                        <li class="home">
                            <a href="index.html">Home</a>
                            <span><i class="fa fa-angle-right"></i></span>
                        </li>
                        <li class="category3"><span>Shopping Cart</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="cart-area-start">
    <div class="container">
        <!-- Shopping Cart Table -->
        <div class="row">
            <div class="col-md-12">
                <div class="table-responsive">
                    <table class="cart-table">
                        <thead>
                            <tr>
                                <th>Product</th>
                                <th>Product name</th>
                                <th>Unit Price</th>
                                <th>Qty</th>
                                <th>Subtotal</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.ShoppingCart.ShoppingCartItems)
                            {
                                <tr>
                                    <td>
                                        <a href="#"><img src="~/img/@item.Product.ProductImage" class="img-responsive" alt="" /></a>
                                    </td>
                                    <td>
                                        <h6>@item.Product.ProductName</h6>
                                    </td>
                                    <td>
                                        <div class="cart-price">@item.Product.Price</div>
                                    </td>
                                    <td>
                                        <form asp-controller="ShoppingCart" asp-action="UpdateCart" method="get">
                                            <input type="hidden" value="@item.ShoppingCartItemId" name="id" />
                                            <input type="text" value=" @item.Amount" asp-for="@item.Amount" name="amount">

                                            <button type="submit" style="border:unset; background-color:unset"> <i class="fa fa-refresh" aria-hidden="true"></i></button>
                                        </form>

                                    </td>
                                    <td>
                                        <div class="cart-subtotal">
                                            @(item.Amount * item.Product.Price)
                                        </div>
                                    </td>
                                    <td><a asp-controller="ShoppingCart" asp-action="RemoveFromShoppingCart" asp-route-id="@item.Product.ProductId"><i class="fa fa-times"></i></a></td>
                                </tr>

                            }

                            <tr>
                                <td class="actions-crt" colspan="7">
                                    <div class="">
                                        <div class="col-md-4 col-sm-4 col-xs-4 align-left">
                                            <a class="cbtn" asp-controller="Products" asp-action="Index">Continue Shopping</a>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div class="col-md-12 vendee-clue">
            <div class="shipping coupon cart-totals">
                <ul>
                    <li class="cartSubT">Grand total:    <span> @Model.ShoppingCartTotal  PKR</span></li>
                </ul>
                <a class="proceedbtn" href="#">PROCEED TO CHECK OUT</a>
            </div>
        </div>
    </div>

</div>